version: '2.2'

services:
  custom:
    build: service
    restart: on-failure
    ports:
      - 17102:31337
    stop_grace_period: 3s
    mem_limit: 256M
    memswap_limit: 256M
    pids_limit: 1024
    ulimits: 
      nofile:
        soft: 8192
        hard: 8192
