language: c

# Needed for libgcrypt 1.6
dist: trusty
sudo: required

env:
  - LUA=lua     LUA_VER=5.1 libgcrypt=11
  - LUA=lua     LUA_VER=5.2 libgcrypt=11
  - LUA=lua     LUA_VER=5.3 libgcrypt=11
  - LUA=luajit  LUA_VER=2.0 libgcrypt=11
  - LUA=luajit  LUA_VER=2.1 libgcrypt=11
  - LUA=lua     LUA_VER=5.1 libgcrypt=20
  - LUA=lua     LUA_VER=5.2 libgcrypt=20
  - LUA=lua     LUA_VER=5.3 libgcrypt=20

matrix:
  include:
    # Libgcrypt 1.7.4 https://blog.travis-ci.com/2016-12-13-xcode-82-ga-is-here
    - os: osx
      osx_image: xcode8.2
      env: LUA=lua LUA_VER=5.2

before_install:
  - if [ "$TRAVIS_OS_NAME" = linux ]; then sudo apt-get -qq update; fi
  - if [ "$TRAVIS_OS_NAME" = linux ]; then sudo apt-get install -y libgcrypt${libgcrypt}-dev; fi
  - if [ "$TRAVIS_OS_NAME" = osx ]; then sudo easy_install pip; fi
  - if [ "$TRAVIS_OS_NAME" = osx ]; then export PATH=~/Library/Python/2.7/bin:$PATH; fi
  - pip install --user hererocks cpp-coveralls
  - hererocks lua_install -r^ --$LUA $LUA_VER
  - export PATH=$PATH:$PWD/lua_install/bin
  - eval `luarocks path --bin`

script:
  - if [ "$TRAVIS_OS_NAME" = linux ]; then LIBFLAG=-shared; fi
  - if [ "$TRAVIS_OS_NAME" = osx ]; then LIBFLAG="-bundle -undefined dynamic_lookup -all_load"; fi
  - luarocks make luagcrypt-scm-0.rockspec CFLAGS="-O2 -fPIC -Wall -Wextra -Werror --coverage" LIBFLAG="$LIBFLAG --coverage"
  - lua luagcrypt_test.lua

after_success:
  - coveralls -e lua_install

branches:
  except:
    - appveyor
